name = "wikitimelines"
main = "worker.js"
compatibility_date = "2024-06-09"

[triggers]
crons = ["0 0 * * *"]

[[kv_namespaces]]
binding = "WIKITIMELINES_KV"
id = "4f3a072717264388bf0f1eb02cc253c8"
preview_id = "a5c1791d72744805bb00f11e07ddd419"
